---
title: "Get Metadata from all your blogs built by blogdown"
author: "Jiaxiang Li"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

When you post a lot for your blog site built by `blogdown`, you may want to merge, edit metadata of some of them.
The function `blogdown_meta` go deeper in the `yaml` contents of each `.Rmd` and build a friendly readable `data.frame` to analyze.
This function is inspired by function `count_yaml` in the package `blogdown`.

```{r message=FALSE, warning=FALSE}
library(tidyverse)
library(data.table)
library(add2blog)
library(here)
```

```{r eval=F}
blogdown_meta(dir = "/Users/vija/Downloads/180805_folder_01/tmp_jli/blog_180802/content/post")
```

```{r echo=FALSE, message=FALSE, warning=FALSE}
# data(blogdown_meta_data,internal = F)
load(file.path('..','data','blogdown_meta_data.rda'))
blogdown_meta_data %>% 
  rmarkdown::paged_table()
```

