---
title: "Build a Wallpaper from your Name"
author: "Jiaxiang Li"
date: "`r Sys.Date()`"
output:
  rmarkdown::html_vignette:
    fig_caption: yes
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

Inspired by Swanson (2015) and Chisato (2018), I create functions `matrix_name` and `graph_fun`.

```{r fig.cap = "The figure from my name."}
library(dplyr)
library(stringr)
library(tibble)
library(tidyr)
library(ggplot2)
library(data.table)
library(add2blog)
matrix_me <- 
    add2blog::matrix_name('jiaxiangli',n = 10)
add2blog::graph_fun(matrix_me,fontsize=3)
```

## Reference {-}

Swanson, Ana. 2015. “10 Stunning Images Show the Beauty Hidden in Pi.” 2015. https://www.washingtonpost.com/news/wonk/wp/2015/03/14/10-stunning-images-show-the-beauty-hidden-in-pi/?noredirect=on&utm_term=.614dbc50c9aa.

Chisato. 2018. “VISUAL Art with Pi Using Ggplot2 & Circlize.” 2018. https://chichacha.netlify.com/2018/10/13/visual-art-with-pi-using-ggplot2-circlize/.


